# Summary

First off, well done! You have now learned how to wrangle, visualise and analyse network data. One final word, this course has presented the process of network analysis in a linear fashion with each step building on the next. That is on purpose - to help you build a project by the end of the semester. However, this process is iterative. Always be mindful of the science behind the data science. Just because the data might tell you something, the science - the process - you used to get there is your responsibility. You need to make sure the data are clean and as representative as possible. Or that you don't make extrapolations that go beyond your data. Don't be so in love with the findings that you miss that you need to clean the data a little more. It is always a best practice to keep a record of all of your work and understand what the data's limits are (i.e. who is missing?, who could be missing?). Always be transparent about your process and your limitations.

I hope you have enjoyed the course.

## Where Now?

There is even more to social network analysis! If this course has sparked a fire for you - I hope it has - then there is even more for you to learn. Consider learning more about different types of analysis you can do on your network.
