# Unit 3

## Learning Elements

In this unit, we will cover how to analyse network data. There are three basic units of network analysis. You may wish to analyse the individuals in the network (a micro, or the smallest unit of analysis). In this instance, you may want to analyse 'well connected' individuals in the network. The next level up are the communities in the network. There may be latent groups of connected individuals who are more connected internally (to each other) than to others in the network. How segmented a network is, or in which community an individual is in might be of particular interest. Finally, the largest unit of analysis is the network itself. In this instance, you might want to analyse characteristics about the entire group or comparing characteristics across groups.

By the end of this unit you will:

1.  Learn the basic idea of centrality in networks

2.  Apply community detecting algorithms

3.  Study global-level network characteristics

4.  Measure symbolic connections between individuals and groups - a principle known as duality

## Project Milestones

| Milestone (assignments linked) | Explanation |
|----|----|
| [Final Project](Final%20Project%20Instructions.qmd) | Students will perform an exploratory analysis using the data they have been working on all semester long. The aim of this project is for you to do an in-depth exploration which includes descriptions, visualisations, and some primary analysis.   |

## Workforce Preparation

There is a lot of technical language in Unit 3. If I were to say to you that person X in the network has a higher betweenness centrality than person Y, the chances are that you would not really understand what I am talking about. A key aspect to successful network analysis is translating your analysis into real terms and action-items. While working on your project, think of substantive questions like, who are the most popular people in this network? Are people in this network more or less interactive than those in another network? These are much more actionable than questions like how in this network has the highest degree centrality? Is one network more or less transitive than another? Believe it or not, those are the same questions. However, your boss or stakeholders are much more likely to understand the first set than they are the second set.

Enjoy Unit!
