# Unit 2

## Learning Elements

In this unit, we will cover how to visualise network data. I maintain that visualisations serve two main purposes. One for you, the data scientist and one for your constituents. As such, visualisations can tell you more about your data. Visualising your network might inform you that you need to do some more cleaning (self loops, extraneous nodes etc.). It might even drive some of your questions that need answering about this network. For example, seeing that there are a few highly central figures in the network may influence you to ask specific questions about those individuals. Additionally, you need to create visualisations that engage stakeholders and tell the story of your analysis.

By the end of this unit you will:

1.  Produce basic (clean), intermediate (storytelling), and more advanced (engaging) visualisations.

2.  Understand that visuals can tell a story about your network.

3.  Learn about visual accessibility.

## Project Milestones

| Milestone (assignments linked) | Explanation |
|----|----|
| [Data Exploration](A3_Data%20Exploration.qmd) | Students will give descriptions of the network data they are using. They will discuss possible transformations to the data that they will need to perform before analysing. They may also provide basic visualisations to demonstrate this. |
| [Visualisations](A4_Visualisations.qmd) | Students will provide multiple visualisations of the network they are studying. This assignment requires students to demonstrate they have learned how to make basic visualization, clean visualization, and more advanced visualisations (i.e. at least one dynamic or interactive version of their network). |

## Workforce Preparation

Visualisaion can be an effective form of communication. It can also confuse, if not done well. Network data may not be the most intuitive visualistions to look at. Although, their novelty make for an attractive visualisation, people are not as used to interpreting them as they are other charts or graphs. Be mindful, when visualising your networks, of their readability. Use titles that are descriptive. For example, if you alter the node sizes to reflect popular people (highly central nodes) consider a title that describes this.

Enjoy Unit 2!
